export const API_ENDPOINTS = {
    AUTH: {
        REGISTER: '/auth/register',
        VERIFY_OTP: '/auth/verify-otp',
        LOGIN: '/auth/login',
        LOGOUT: '/auth/logout',
        ME: '/auth/me',
    },
    USER: {
        GET: '/user',
        UPDATE: '/user',
        DELETE: '/user',
        ALL: '/user/all',
    },
    ROLE_REQUEST: {
        CREATE: '/role-request',
        MY_REQUESTS: '/role-request/me',
        ALL: '/role-request/all',
        PENDING: '/role-request/pending',
        BY_ID: (id: number) => `/role-request/${id}`,
        UPDATE_STATUS: (id: number) => `/role-request/${id}/status`,
        DELETE: (id: number) => `/role-request/${id}`,
    },
    SUPPLIER: {
        PROFILE: '/supplier/profile',
        WAREHOUSE: '/supplier/warehouse',
        PRODUCTS: '/supplier/products',
        PRODUCT_BY_ID: (id: number) => `/supplier/products/${id}`,
        INVENTORY: '/supplier/inventory',
        INVENTORY_BY_ID: (id: number) => `/supplier/inventory/${id}`,
        TRANSPORTERS: '/supplier/transporters',
        TRANSPORTER_BY_ID: (id: number) => `/supplier/transporters/${id}`,
        ORDERS: '/supplier/orders',
        DISTRIBUTORS: '/supplier/distributors',
        SUPPLIERS: '/supplier/suppliers',
    },
    DISTRIBUTOR: {
        PROFILE: '/distributor/profile',
        TRANSPORTERS: '/distributor/transporters',
        TRANSPORTER_BY_ID: (id: number) => `/distributor/transporters/${id}`,
        ASSIGNED_ORDERS: '/distributor/orders/assigned',
        HELD_ORDERS: '/distributor/orders/held',
        ACCEPT_LEG: (legId: number) => `/distributor/legs/${legId}/accept`,
        REJECT_LEG: (legId: number) => `/distributor/legs/${legId}/reject`,
        CONFIRM_RECEIPT: (legId: number) => `/distributor/legs/${legId}/confirm-receipt`,
        SHIP_LEG: (legId: number) => `/distributor/legs/${legId}/ship`,
        FORWARD_ORDER: (orderId: number) => `/distributor/orders/${orderId}/forward`,
        OUTGOING_LEGS: '/distributor/legs/outgoing',
        LEG_BY_ID: (legId: number) => `/distributor/legs/${legId}`,
        DISTRIBUTORS: '/distributor/distributors',
    },
    ORDER: {
        PRODUCTS: '/order/products',
        CREATE: '/order',
        MY_ORDERS: '/order/my-orders',
        BY_ID: (id: number) => `/order/${id}`,
        CANCEL: (id: number) => `/order/${id}/cancel`,
        CONFIRM_DELIVERY: (id: number) => `/order/${id}/confirm-delivery`,
        APPROVE: (id: number) => `/order/${id}/approve`,
        REJECT: (id: number) => `/order/${id}/reject`,
        REASSIGN: (id: number) => `/order/${id}/reassign`,
        SHIP: (orderId: number, legId: number) => `/order/${orderId}/legs/${legId}/ship`,
    },
    VERIFICATION: {
        VERIFY_QR: (token: string) => `/verify?token=${encodeURIComponent(token)}`,
        ORDER_QR: (orderId: number) => `/verify/order/${orderId}/qr`,
    },
} as const;